name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image multi-arch
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/upvote-rss:${{ github.ref }},ghcr.io/${{ github.repository_owner }}/upvote-rss:latest
          platforms: linux/amd64,linux/arm64

      - name: Update Release Notes
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          body: |
            Release notes:
            - Docker image built and pushed for both linux/amd64 and linux/arm64.
            - Image tagged with ${{ github.ref }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}